-- AegisDB — canonical schema (PostgreSQL 16+).
-- Naming: tbl_ prefix, pk_ primary keys, idx_ indexes. No physical FKs —
-- relational integrity is maintained at the application layer (backend doc §9).
-- This is the AUTHORITATIVE production schema, applied via `vela-gateway migrate`
-- and tracked in schema_migrations (see internal/bootstrap/migrate.go).
--
-- This file is a BASELINE: migrations 0001–0044 of the MySQL era collapsed into
-- the single shape they added up to. Every statement is idempotent
-- (CREATE TABLE / CREATE INDEX … IF NOT EXISTS) so applying it twice is a no-op
-- — test harnesses build the schema from this file and then let Migrate() run
-- against an empty ledger.
--
-- Types: BIGINT identity for surrogate keys, TIMESTAMPTZ for instants, TEXT for
-- unbounded blobs. Note VARCHAR(64) — not CHAR(64) — for the audit hash columns:
-- PostgreSQL's char(n) is blank-padded and would come back to Go with trailing
-- spaces, breaking the string comparison the hash chain relies on
-- (internal/service/audit_chain.go).

-- ---------------------------------------------------------------- identity ---

CREATE TABLE IF NOT EXISTS tbl_role (
  id                BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  code              VARCHAR(64)  NOT NULL,
  name              VARCHAR(64)  NOT NULL,
  layer             VARCHAR(32)  NOT NULL,
  description       VARCHAR(255),
  default_conn_role VARCHAR(64),
  can_approve       BOOLEAN      NOT NULL DEFAULT false,
  icon              VARCHAR(32),
  created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
  CONSTRAINT pk_tbl_role PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_role_code ON tbl_role (code);

CREATE TABLE IF NOT EXISTS tbl_user (
  id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  name          VARCHAR(64)  NOT NULL,
  email         VARCHAR(128) NOT NULL,
  role_id       BIGINT       NOT NULL,
  status        VARCHAR(16)  NOT NULL DEFAULT 'active',  -- active|disabled|invited
  kind          VARCHAR(16)  NOT NULL DEFAULT 'human',   -- human|service (migration 0021)
  mfa_enabled   BOOLEAN      NOT NULL DEFAULT false,
  mfa_secret    VARCHAR(64),                        -- base32 TOTP secret (RFC 6238)
  mfa_last_ctr  BIGINT       NOT NULL DEFAULT 0,    -- last consumed TOTP counter (anti-replay)
  token_version BIGINT       NOT NULL DEFAULT 0,    -- session generation; bumped to revoke tokens
  password_hash VARCHAR(255),
  dept          VARCHAR(64),
  initials      VARCHAR(8),
  last_active   VARCHAR(32),
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
  CONSTRAINT pk_tbl_user PRIMARY KEY (id)
);
-- Uniqueness is on lower(email), not email: MySQL's utf8mb4_unicode_ci made
-- login case-insensitive for free, PostgreSQL does not. The functional index
-- restores that behaviour and is what the login lookup matches against.
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_email ON tbl_user (lower(email));
CREATE INDEX IF NOT EXISTS idx_user_role ON tbl_user (role_id);

CREATE TABLE IF NOT EXISTS tbl_user_tag (
  user_id BIGINT      NOT NULL,
  tag     VARCHAR(64) NOT NULL,
  CONSTRAINT pk_tbl_user_tag PRIMARY KEY (user_id, tag)
);

CREATE TABLE IF NOT EXISTS tbl_role_menu (
  role_id  BIGINT      NOT NULL,
  menu_key VARCHAR(32) NOT NULL,                  -- terminal|approve|db|rules|perms|audit|settings
  enabled  BOOLEAN     NOT NULL DEFAULT false,
  CONSTRAINT pk_tbl_role_menu PRIMARY KEY (role_id, menu_key)
);

CREATE TABLE IF NOT EXISTS tbl_role_member (
  role_id BIGINT NOT NULL,
  user_id BIGINT NOT NULL,
  CONSTRAINT pk_tbl_role_member PRIMARY KEY (role_id, user_id)
);

CREATE TABLE IF NOT EXISTS tbl_role_tag (
  role_id BIGINT      NOT NULL,
  tag     VARCHAR(64) NOT NULL,                    -- grants access to connections carrying this tag
  CONSTRAINT pk_tbl_role_tag PRIMARY KEY (role_id, tag)
);

CREATE TABLE IF NOT EXISTS tbl_role_capability (
  role_id    BIGINT      NOT NULL,
  capability VARCHAR(32) NOT NULL,                -- select|write|ddl|grant|conn|approve
  tier_code  VARCHAR(32) NOT NULL,                -- tbl_env_tier.code (renamed from env, migration 0016)
  level      VARCHAR(16) NOT NULL,                -- allow|approve|deny
  CONSTRAINT pk_tbl_role_capability PRIMARY KEY (role_id, capability, tier_code)
);

-- --------------------------------------------------- environments & targets ---

CREATE TABLE IF NOT EXISTS tbl_env_tier (
  code              VARCHAR(32)  NOT NULL,        -- prod|gli|staging|uat|dev
  display_name      VARCHAR(64)  NOT NULL,
  sort_order        INT          NOT NULL DEFAULT 0,
  require_mfa       BOOLEAN      NOT NULL DEFAULT false,
  danger_banner     BOOLEAN      NOT NULL DEFAULT false,
  counts_in_pending BOOLEAN      NOT NULL DEFAULT false,
  scan_baseline     BOOLEAN      NOT NULL DEFAULT false,
  strict_nowhere    BOOLEAN      NOT NULL DEFAULT true,   -- migration 0030
  conn_layer        VARCHAR(64)  NOT NULL DEFAULT '',
  default_role      VARCHAR(64)  NOT NULL DEFAULT '',
  CONSTRAINT pk_tbl_env_tier PRIMARY KEY (code)
);

CREATE TABLE IF NOT EXISTS tbl_environment (
  code         VARCHAR(32) NOT NULL,
  display_name VARCHAR(64) NOT NULL,
  tier_code    VARCHAR(32) NOT NULL,
  sort_order   INT         NOT NULL DEFAULT 0,
  CONSTRAINT pk_tbl_environment PRIMARY KEY (code)
);
CREATE INDEX IF NOT EXISTS idx_environment_tier ON tbl_environment (tier_code);

CREATE TABLE IF NOT EXISTS tbl_connection (
  id           BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  name         VARCHAR(64)  NOT NULL,
  engine       VARCHAR(32)  NOT NULL,             -- mysql/postgres/clickhouse/redis/tidb
  host         VARCHAR(128) NOT NULL,
  port         INT          NOT NULL,
  env          VARCHAR(32)  NOT NULL,             -- tbl_environment.code
  policy       VARCHAR(32)  NOT NULL,             -- strict|approve-1|audit-only
  default_role VARCHAR(64),
  layer        VARCHAR(64),
  username     VARCHAR(64),                        -- real-execution credentials
  password     VARCHAR(255),
  -- TEXT,不是 VARCHAR(n)。**全库所有 db_name 列的口径都在这里**。
  --
  -- 这一列装的是「目标库」,而目标库对 sqlite 引擎就是一个**文件绝对路径**。路径长度
  -- 没有上限可言 —— 128 从来就是个错的数字,只是旧测试跑在 SQLite 上(它不检查写入
  -- 长度)所以一直没有暴露;换到 PG 上,一条 macOS 默认 TMPDIR 下的临时路径就足够
  -- 把它撑爆,报 value too long for type character varying(128)。
  --
  -- 别的表里的 db_name 是这一列的**拷贝**(审批单/审计/执行窗口/导出/异步任务/发布/
  -- 元数据…… 记的都是「这条命令打到哪个库」),所以它们必须一样宽,否则连接建得出来,
  -- 而针对它开的第一张审批单写不进去。PG 上 TEXT 与 VARCHAR(n) 存储方式完全相同,
  -- 那个上限不换来任何好处,只换来一次「路径够长才炸」的写入失败。
  db_name      TEXT,                               -- default schema / sqlite file
  tags         VARCHAR(255),                       -- comma-separated labels for group access
  status       VARCHAR(16)  NOT NULL DEFAULT 'online',  -- online|maint
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  CONSTRAINT pk_tbl_connection PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_connection_name ON tbl_connection (name);
CREATE INDEX IF NOT EXISTS idx_connection_env ON tbl_connection (env);

CREATE TABLE IF NOT EXISTS tbl_risk_command (
  command   VARCHAR(32) NOT NULL,                 -- DROP/TRUNCATE/...
  tier_code VARCHAR(32) NOT NULL,                 -- tbl_env_tier.code (renamed from env, migration 0016)
  level     VARCHAR(16) NOT NULL DEFAULT 'high',  -- high|mid|off
  CONSTRAINT pk_tbl_risk_command PRIMARY KEY (command, tier_code)
);

CREATE TABLE IF NOT EXISTS tbl_schema_object (
  id            BIGINT      GENERATED BY DEFAULT AS IDENTITY,
  connection_id BIGINT      NOT NULL,
  db_name       TEXT         NOT NULL,             -- renamed from `database`, migration 0040;宽度同 tbl_connection.db_name
  table_name    VARCHAR(64) NOT NULL,
  CONSTRAINT pk_tbl_schema_object PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_schema_conn ON tbl_schema_object (connection_id);

CREATE TABLE IF NOT EXISTS tbl_project (
  id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  name        VARCHAR(64)  NOT NULL,
  owner       VARCHAR(64),                        -- 负责人 / 团队，自由文本
  description VARCHAR(512),
  created_by  BIGINT       NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ,
  updated_at  TIMESTAMPTZ,
  CONSTRAINT pk_tbl_project PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_project_name ON tbl_project (name);

CREATE TABLE IF NOT EXISTS tbl_database_project (
  id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  connection_id BIGINT       NOT NULL,
  db_name       TEXT         NOT NULL,             -- 宽度同 tbl_connection.db_name
  project_id    BIGINT       NOT NULL,
  created_by    BIGINT       NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ,
  updated_at    TIMESTAMPTZ,
  CONSTRAINT pk_tbl_database_project PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_db_project ON tbl_database_project (connection_id, db_name);
CREATE INDEX IF NOT EXISTS idx_db_project_project ON tbl_database_project (project_id);

-- ----------------------------------------------------------------- approval ---

CREATE TABLE IF NOT EXISTS tbl_approval (
  id               BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  ap_no            VARCHAR(32)  NOT NULL,
  connection_id    BIGINT       NOT NULL,
  env              VARCHAR(32)  NOT NULL,
  tier_code        VARCHAR(32),                            -- NOT NULL dropped by migration 0038
  instance         VARCHAR(64)  NOT NULL,
  command          TEXT         NOT NULL,
  script_upload_id BIGINT       NOT NULL DEFAULT 0,
  script_sha256    VARCHAR(64)  NOT NULL DEFAULT '',
  keyword          VARCHAR(32),
  db_name          TEXT,                                   -- selected target database;宽度同 tbl_connection.db_name
  initiator_id     BIGINT       NOT NULL,
  initiator        VARCHAR(64),
  reason           VARCHAR(512),
  risk_level       VARCHAR(16)  NOT NULL,                  -- high|mid|low
  status           VARCHAR(16)  NOT NULL DEFAULT 'pending', -- pending|approved|rejected|expired
  audit_id         VARCHAR(32),
  external_task_id VARCHAR(128) NOT NULL DEFAULT '',
  release_id       BIGINT       NOT NULL DEFAULT 0,
  export_job_id    BIGINT       NOT NULL DEFAULT 0,
  window_id        BIGINT       NOT NULL DEFAULT 0,
  result           TEXT,                                   -- execution output once approved
  result_rows      INT,
  exec_status      VARCHAR(16),
  escalated        BOOLEAN      NOT NULL DEFAULT false,    -- timeout escalation fired once
  executed_at      TIMESTAMPTZ,
  decided_at       TIMESTAMPTZ,                            -- when approved/rejected
  created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
  CONSTRAINT pk_tbl_approval PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_approval_apno ON tbl_approval (ap_no);
CREATE INDEX IF NOT EXISTS idx_approval_status ON tbl_approval (status);
CREATE INDEX IF NOT EXISTS idx_approval_initiator ON tbl_approval (initiator_id);
CREATE INDEX IF NOT EXISTS idx_approval_ext ON tbl_approval (external_task_id);
CREATE INDEX IF NOT EXISTS idx_approval_release ON tbl_approval (release_id);
CREATE INDEX IF NOT EXISTS idx_approval_export ON tbl_approval (export_job_id);
CREATE INDEX IF NOT EXISTS idx_approval_window ON tbl_approval (window_id);

CREATE TABLE IF NOT EXISTS tbl_approval_step (
  id          BIGINT      GENERATED BY DEFAULT AS IDENTITY,
  approval_id BIGINT      NOT NULL,
  step_order  INT         NOT NULL,
  approver_id BIGINT      NOT NULL,
  approver    VARCHAR(64),
  status      VARCHAR(16) NOT NULL DEFAULT 'waiting', -- waiting|active|approved|rejected
  acted_at    TIMESTAMPTZ,
  CONSTRAINT pk_tbl_approval_step PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_step_approval ON tbl_approval_step (approval_id);
CREATE INDEX IF NOT EXISTS idx_approval_step_approver ON tbl_approval_step (approver_id);

CREATE TABLE IF NOT EXISTS tbl_exec_window (
  id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  name          VARCHAR(64)  NOT NULL,
  enabled       BOOLEAN      NOT NULL DEFAULT true,
  connection_id BIGINT       NOT NULL,
  db_name       TEXT         NOT NULL,             -- 宽度同 tbl_connection.db_name
  kind          VARCHAR(16)  NOT NULL,
  timezone      VARCHAR(64)  NOT NULL,
  starts_at     TIMESTAMPTZ,
  ends_at       TIMESTAMPTZ,
  weekdays      VARCHAR(32),
  start_min     INT          NOT NULL DEFAULT 0,
  end_min       INT          NOT NULL DEFAULT 0,
  not_after     TIMESTAMPTZ,
  reason        VARCHAR(255),
  status        VARCHAR(16)  NOT NULL DEFAULT 'pending',  -- migration 0033
  approval_id   BIGINT       NOT NULL DEFAULT 0,
  ap_no         VARCHAR(32),
  decided_at    TIMESTAMPTZ,
  created_by    BIGINT       NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ,
  updated_at    TIMESTAMPTZ,
  CONSTRAINT pk_tbl_exec_window PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_window_scope ON tbl_exec_window (connection_id, db_name);

-- -------------------------------------------------------------------- audit ---

CREATE TABLE IF NOT EXISTS tbl_audit_log (
  id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  occurred_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
  actor_id      BIGINT       NOT NULL,
  actor_name    VARCHAR(64),
  connection_id BIGINT,
  instance      VARCHAR(64),
  db_name       TEXT,                              -- 宽度同 tbl_connection.db_name
  env           VARCHAR(32)  NOT NULL DEFAULT '',
  tier_code     VARCHAR(32),                       -- NOT NULL dropped by migration 0038
  command       TEXT         NOT NULL,
  risk          VARCHAR(16)  NOT NULL,             -- high|mid|low
  result        VARCHAR(16)  NOT NULL,             -- executed|pending|rejected|warn
  approval_no   VARCHAR(32),
  operator      VARCHAR(128) NOT NULL DEFAULT '',
  prev_hash     VARCHAR(64),
  hash          VARCHAR(64)  NOT NULL,             -- SHA256(prev_hash + payload) chain
  CONSTRAINT pk_tbl_audit_log PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_audit_time ON tbl_audit_log (occurred_at);
CREATE INDEX IF NOT EXISTS idx_audit_actor ON tbl_audit_log (actor_id);
CREATE INDEX IF NOT EXISTS idx_audit_risk ON tbl_audit_log (risk);
-- Hash-chain linearity enforced at the database layer: two rows cannot chain
-- onto the same predecessor. The single genesis row uses '' as its predecessor.
CREATE UNIQUE INDEX IF NOT EXISTS uk_audit_prev ON tbl_audit_log (prev_hash);

-- ------------------------------------------------------------------- notify ---

CREATE TABLE IF NOT EXISTS tbl_notification (
  id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  user_id    BIGINT       NOT NULL,
  type       VARCHAR(32)  NOT NULL,                -- approval-approved|approval-rejected|approval-expired
  title      VARCHAR(128) NOT NULL,
  body       VARCHAR(512),
  ref_no     VARCHAR(32),                          -- related ticket, e.g. AP-2295
  is_read    BOOLEAN      NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
  CONSTRAINT pk_tbl_notification PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_notif_user ON tbl_notification (user_id);

CREATE TABLE IF NOT EXISTS tbl_webhook_config (
  id        BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  endpoint  VARCHAR(255) NOT NULL,
  secret    VARCHAR(255) NOT NULL DEFAULT '',      -- widened for the encrypted form, migration 0036
  events    VARCHAR(255) NOT NULL,                 -- intercept,approve,exec,login
  retry_max INT          NOT NULL DEFAULT 5,
  enabled   BOOLEAN      NOT NULL DEFAULT true,
  CONSTRAINT pk_tbl_webhook_config PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tbl_webhook_delivery (
  id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  event      VARCHAR(32)  NOT NULL,                -- intercept|approve|exec|login|test
  endpoint   VARCHAR(255),
  success    BOOLEAN      NOT NULL,
  status     VARCHAR(128),                         -- "200 OK" or error text
  attempts   INT          NOT NULL,
  created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
  CONSTRAINT pk_tbl_webhook_delivery PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tbl_setting (
  k VARCHAR(64) NOT NULL,
  v TEXT        NOT NULL,
  CONSTRAINT pk_tbl_setting PRIMARY KEY (k)
);

-- ------------------------------------------------------------ jobs & export ---

CREATE TABLE IF NOT EXISTS tbl_async_job (
  id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  user_id       BIGINT       NOT NULL,
  connection_id BIGINT       NOT NULL,
  instance      VARCHAR(96)  NOT NULL DEFAULT '',
  db_name       TEXT         NOT NULL DEFAULT '',  -- 宽度同 tbl_connection.db_name
  sql_text      TEXT,                                     -- renamed from `sql`, migration 0041
  reason        VARCHAR(512) NOT NULL DEFAULT '',
  status        VARCHAR(16)  NOT NULL DEFAULT 'pending',  -- pending|running|done|failed
  risk          VARCHAR(16)  NOT NULL DEFAULT '',
  log           TEXT,
  row_count     INT          NOT NULL DEFAULT 0,          -- renamed from `rows`, migration 0041
  error         VARCHAR(512) NOT NULL DEFAULT '',
  created_at    TIMESTAMPTZ,
  started_at    TIMESTAMPTZ,
  finished_at   TIMESTAMPTZ,
  CONSTRAINT pk_tbl_async_job PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_async_user ON tbl_async_job (user_id);

CREATE TABLE IF NOT EXISTS tbl_export_job (
  id                BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  user_id           BIGINT       NOT NULL,
  connection_id     BIGINT,
  instance          VARCHAR(96),
  db_name           TEXT,                              -- 宽度同 tbl_connection.db_name
  sql_text          TEXT,                                     -- renamed from `sql`, migration 0042
  name              VARCHAR(128),
  status            VARCHAR(16)  NOT NULL DEFAULT 'pending',  -- pending|running|done|failed
  include_sensitive BOOLEAN      NOT NULL DEFAULT false,
  approval_id       BIGINT       NOT NULL DEFAULT 0,
  ap_no             VARCHAR(32),
  row_count         INT,                                      -- renamed from `rows`, migration 0042
  bytes             BIGINT,                                   -- total encrypted size across parts
  parts             INT,                                      -- number of ~100MB CSV files
  files             TEXT,                                     -- newline-joined part paths
  password          VARCHAR(128),
  error             VARCHAR(255),
  created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
  finished_at       TIMESTAMPTZ,
  CONSTRAINT pk_tbl_export_job PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_export_user ON tbl_export_job (user_id);
CREATE INDEX IF NOT EXISTS idx_export_approval ON tbl_export_job (approval_id);

CREATE TABLE IF NOT EXISTS tbl_script_upload (
  id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  user_id    BIGINT       NOT NULL,
  filename   VARCHAR(255) NOT NULL,
  path       VARCHAR(512),
  size       BIGINT,
  source     VARCHAR(16),                             -- upload|terminal
  created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
  CONSTRAINT pk_tbl_script_upload PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_upload_user ON tbl_script_upload (user_id);

CREATE TABLE IF NOT EXISTS tbl_terminal_snippet (
  id         BIGINT      GENERATED BY DEFAULT AS IDENTITY,
  user_id    BIGINT      NOT NULL,
  name       VARCHAR(64) NOT NULL,
  body       TEXT        NOT NULL,
  slot       INT         NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ,
  CONSTRAINT pk_tbl_terminal_snippet PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_snippet_user ON tbl_terminal_snippet (user_id);

-- --------------------------------------------------- review, pipeline, release ---

CREATE TABLE IF NOT EXISTS tbl_sql_review_rule (
  id         BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  code       VARCHAR(64)  NOT NULL,
  name       VARCHAR(128) NOT NULL,
  dialect    VARCHAR(64)  NOT NULL DEFAULT 'all',
  category   VARCHAR(32)  NOT NULL,
  level      VARCHAR(16)  NOT NULL DEFAULT 'warn',
  kind       VARCHAR(16)  NOT NULL DEFAULT 'builtin',
  enabled    BOOLEAN      NOT NULL DEFAULT true,
  params     TEXT,
  message    VARCHAR(512),
  spec       VARCHAR(16)  NOT NULL DEFAULT '',       -- migration 0026: which written spec the rule comes from
  spec_ref   VARCHAR(128) NOT NULL DEFAULT '',       -- migration 0026: the clause within that spec
  sort_order INT          NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ,
  CONSTRAINT pk_tbl_sql_review_rule PRIMARY KEY (id)
);
-- Uniqueness is on lower(code), not code: a custom rule's code is free text the
-- operator types, and under MySQL's utf8mb4_unicode_ci "custom.Foo" collided with
-- "custom.foo" for free. PostgreSQL does not fold case, so the functional index
-- restores that behaviour — storage still keeps the operator's original casing.
CREATE UNIQUE INDEX IF NOT EXISTS idx_review_code ON tbl_sql_review_rule (lower(code));

CREATE TABLE IF NOT EXISTS tbl_pipeline (
  id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  name        VARCHAR(128) NOT NULL,
  description VARCHAR(512),
  tier_code   VARCHAR(32),
  enabled     BOOLEAN      NOT NULL DEFAULT true,
  is_default  BOOLEAN      NOT NULL DEFAULT false,
  created_by  BIGINT       NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ,
  updated_at  TIMESTAMPTZ,
  CONSTRAINT pk_tbl_pipeline PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_pipeline_tier ON tbl_pipeline (tier_code);

CREATE TABLE IF NOT EXISTS tbl_pipeline_stage (
  id          BIGINT      GENERATED BY DEFAULT AS IDENTITY,
  pipeline_id BIGINT      NOT NULL,
  step_order  INT         NOT NULL,
  name        VARCHAR(64) NOT NULL,
  type        VARCHAR(16) NOT NULL,
  config      TEXT,
  on_failure  VARCHAR(16) NOT NULL DEFAULT 'abort',
  CONSTRAINT pk_tbl_pipeline_stage PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_pstage_pipeline ON tbl_pipeline_stage (pipeline_id);

CREATE TABLE IF NOT EXISTS tbl_release (
  id               BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  rel_no           VARCHAR(32)  NOT NULL,
  title            VARCHAR(128) NOT NULL,
  pipeline_id      BIGINT       NOT NULL,
  pipeline_name    VARCHAR(128),
  connection_id    BIGINT       NOT NULL,
  instance         VARCHAR(96),
  db_name          TEXT,                                   -- 宽度同 tbl_connection.db_name
  env              VARCHAR(32),
  tier_code        VARCHAR(32),
  engine           VARCHAR(32),
  sql_text         TEXT,                                  -- renamed from `sql`, migration 0043
  script_upload_id BIGINT       NOT NULL DEFAULT 0,
  script_sha256    VARCHAR(64),
  reason           VARCHAR(512),
  change_type      VARCHAR(8)   NOT NULL DEFAULT '',      -- migration 0022: ddl|dml
  project_id       BIGINT       NOT NULL DEFAULT 0,       -- migration 0025
  project_name     VARCHAR(64),
  source           VARCHAR(16)  NOT NULL DEFAULT 'console', -- migration 0020: console|api
  client_id        BIGINT       NOT NULL DEFAULT 0,
  client_name      VARCHAR(64),
  external_ref     VARCHAR(128),
  idem_key         VARCHAR(160),
  creator_id       BIGINT       NOT NULL,
  creator          VARCHAR(64),
  status           VARCHAR(16)  NOT NULL DEFAULT 'pending',
  risk             VARCHAR(16),
  error            VARCHAR(512),
  created_at       TIMESTAMPTZ,
  started_at       TIMESTAMPTZ,
  finished_at      TIMESTAMPTZ,
  CONSTRAINT pk_tbl_release PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_release_relno ON tbl_release (rel_no);
CREATE INDEX IF NOT EXISTS idx_release_creator ON tbl_release (creator_id);
CREATE INDEX IF NOT EXISTS idx_release_status ON tbl_release (status);
CREATE INDEX IF NOT EXISTS idx_release_extref ON tbl_release (external_ref);
CREATE INDEX IF NOT EXISTS idx_release_project ON tbl_release (project_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_release_idem ON tbl_release (idem_key);

CREATE TABLE IF NOT EXISTS tbl_release_stage (
  id           BIGINT      GENERATED BY DEFAULT AS IDENTITY,
  release_id   BIGINT      NOT NULL,
  step_order   INT         NOT NULL,
  name         VARCHAR(64) NOT NULL,
  type         VARCHAR(16) NOT NULL,
  config       TEXT,
  on_failure   VARCHAR(16) NOT NULL DEFAULT 'abort',
  status       VARCHAR(16) NOT NULL DEFAULT 'pending',
  log          TEXT,
  findings     TEXT,
  approval_id  BIGINT      NOT NULL DEFAULT 0,
  approval_no  VARCHAR(32),
  confirmed_by VARCHAR(64) NOT NULL DEFAULT '',   -- migration 0024
  row_count    INT         NOT NULL DEFAULT 0,    -- renamed from `rows`, migration 0044
  started_at   TIMESTAMPTZ,
  finished_at  TIMESTAMPTZ,
  CONSTRAINT pk_tbl_release_stage PRIMARY KEY (id)
);
CREATE INDEX IF NOT EXISTS idx_rstage_release ON tbl_release_stage (release_id);
CREATE INDEX IF NOT EXISTS idx_rstage_approval ON tbl_release_stage (approval_id);

CREATE TABLE IF NOT EXISTS tbl_api_client (
  id           BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  name         VARCHAR(64)  NOT NULL,
  api_key      VARCHAR(64)  NOT NULL,             -- renamed from `key`, migration 0039
  secret_hash  VARCHAR(255) NOT NULL,
  user_id      BIGINT       NOT NULL,
  user_name    VARCHAR(64),
  allow_ips    VARCHAR(512),
  scopes       VARCHAR(255) NOT NULL,
  pipeline_id  BIGINT       NOT NULL DEFAULT 0,   -- migration 0023
  enabled      BOOLEAN      NOT NULL DEFAULT true,
  last_used_at TIMESTAMPTZ,
  created_by   BIGINT       NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ,
  CONSTRAINT pk_tbl_api_client PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_apiclient_key ON tbl_api_client (api_key);

-- -------------------------------------------------------- masking & metadata ---

CREATE TABLE IF NOT EXISTS tbl_sensitive_column (
  id          BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  table_name  VARCHAR(128) NOT NULL,                     -- '*' = 所有表
  column_name VARCHAR(128) NOT NULL,
  mask_style  VARCHAR(16)  NOT NULL DEFAULT 'partial',   -- partial|full|hash
  enabled     BOOLEAN      NOT NULL DEFAULT true,
  note        VARCHAR(255),                              -- 为什么它是敏感的，给后来人看
  created_by  BIGINT       NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ,
  updated_at  TIMESTAMPTZ,
  CONSTRAINT pk_tbl_sensitive_column PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_sensitive_col ON tbl_sensitive_column (table_name, column_name);

CREATE TABLE IF NOT EXISTS tbl_meta_table (
  id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  connection_id BIGINT       NOT NULL,
  db_name       TEXT         NOT NULL,             -- 宽度同 tbl_connection.db_name
  schema_name   VARCHAR(128) NOT NULL DEFAULT '',
  table_name    VARCHAR(128) NOT NULL,
  kind          VARCHAR(16)  NOT NULL DEFAULT 'table',   -- table | view
  comment       VARCHAR(512) NOT NULL DEFAULT '',
  synced_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  CONSTRAINT pk_tbl_meta_table PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_meta_table_uniq ON tbl_meta_table (connection_id, db_name, schema_name, table_name);
CREATE INDEX IF NOT EXISTS idx_meta_table_name ON tbl_meta_table (table_name);

CREATE TABLE IF NOT EXISTS tbl_meta_column (
  id            BIGINT       GENERATED BY DEFAULT AS IDENTITY,
  connection_id BIGINT       NOT NULL,
  db_name       TEXT         NOT NULL,             -- 宽度同 tbl_connection.db_name
  schema_name   VARCHAR(128) NOT NULL DEFAULT '',
  table_name    VARCHAR(128) NOT NULL,
  ordinal       INT          NOT NULL DEFAULT 0,
  column_name   VARCHAR(128) NOT NULL,
  data_type     VARCHAR(128) NOT NULL,
  nullable      BOOLEAN      NOT NULL DEFAULT true,
  col_default   VARCHAR(512) NOT NULL DEFAULT '',
  comment       VARCHAR(512) NOT NULL DEFAULT '',
  is_pk         BOOLEAN      NOT NULL DEFAULT false,
  synced_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
  CONSTRAINT pk_tbl_meta_column PRIMARY KEY (id)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_meta_col_uniq ON tbl_meta_column (connection_id, db_name, schema_name, table_name, column_name);
CREATE INDEX IF NOT EXISTS idx_meta_col_scope ON tbl_meta_column (connection_id, db_name, table_name);
CREATE INDEX IF NOT EXISTS idx_meta_col_name ON tbl_meta_column (column_name);

CREATE TABLE IF NOT EXISTS tbl_meta_sync (
  connection_id BIGINT       NOT NULL,
  started_at    TIMESTAMPTZ,
  finished_at   TIMESTAMPTZ,
  db_count      INT          NOT NULL DEFAULT 0,
  table_count   INT          NOT NULL DEFAULT 0,
  column_count  INT          NOT NULL DEFAULT 0,
  err           VARCHAR(512) NOT NULL DEFAULT '',
  CONSTRAINT pk_tbl_meta_sync PRIMARY KEY (connection_id)
);
