-- 0037: 把落库的脚本路径统一成 `/`。
--
-- ## 为什么
--
-- SaveUploadedScript 用 filepath.Join 拼路径,而它用的是**当前这台机器**的分隔符。
-- 在 Windows 上开发时落库的是
--
--   uploads\Lin_Wei\20260908-155637.379_dup-check.sql
--
-- 这一行在 Linux 或 macOS 上读不了 —— 反斜杠不是路径分隔符,整串被当成一个文件名,
-- os.Stat 找不到,接口回「脚本文件不可用或不属于当前用户」。而文件就好端端在那儿。
--
-- ## 这条迁移是"顺手",不是"必需"
--
-- 代码那一侧(service/script_path.go)读的时候两种分隔符都认,所以存量记录已经能用了。
-- 这条只是让库里的数据也干净:留着一半反斜杠一半斜杠,下一个查这张表的人会先怀疑
-- 自己看错了。
--
-- REPLACE 对已经是 `/` 的行是空操作,所以重复执行没有副作用(ADR 0016)。

UPDATE tbl_script_upload SET path = REPLACE(path, '\\', '/') WHERE path LIKE '%\\%';
