package service

// 链的哈希不能跟着时间的**表示**走,只能跟着时刻本身走。
//
// 这是迁 PostgreSQL 时踩到的那一脚:payload 里的时间从前是 a.OccurredAt.Format(
// time.RFC3339),而 RFC3339 带时区偏移 —— 同一个时刻,+08:00 写成
// "2026-09-15T10:54:19+08:00",UTC 写成 "2026-09-15T02:54:19Z"。写入时那行的
// OccurredAt 是 time.Now()(进程本地时区),读回来挂什么 Location 由驱动、列类型和
// 进程的 TZ 一起决定 —— 只要两边不一样,重算的哈希就跟库里存的对不上,于是**每一次**
// 链校验都报「链断了」,而链其实是好的。
//
// 一个恒假的篡改警报比没有警报更糟:它训练人忽略它,最后校验被关掉。

import (
	"testing"
	"time"

	"gorm.io/gorm"

	"velagateway/internal/model"
	"velagateway/internal/repository"
	"velagateway/internal/testsupport"
	"velagateway/pkg/crypto"
)

// 同一时刻,不同 Location,必须算出同一个哈希。
func TestAuditPayload_IsTimezoneIndependent(t *testing.T) {
	inShanghai, err := time.LoadLocation("Asia/Shanghai")
	if err != nil {
		t.Fatalf("load location: %v", err)
	}
	moment := time.Date(2026, 9, 15, 7, 24, 0, 0, time.UTC)

	a := &model.AuditLog{
		OccurredAt: moment.In(inShanghai),
		ActorName:  "林薇", Instance: "prod-1", Command: "select 1",
		Risk: "low", Result: "ok", ApprovalNo: "AP-1",
	}
	b := &model.AuditLog{
		OccurredAt: moment.In(time.UTC),
		ActorName:  "林薇", Instance: "prod-1", Command: "select 1",
		Risk: "low", Result: "ok", ApprovalNo: "AP-1",
	}

	if got, want := string(auditPayload(b)), string(auditPayload(a)); got != want {
		t.Errorf("同一时刻两种时区算出不同 payload:\n +08:00 → %s\n UTC    → %s", want, got)
	}
}

// 版本机制没被绕过:v5 就是当前版,读侧逐版尝试能认出它。
func TestMatchAuditRow_RecognisesV5(t *testing.T) {
	if currentAuditPayloadVersion != 5 {
		t.Fatalf("currentAuditPayloadVersion = %d, want 5", currentAuditPayloadVersion)
	}
	a := &model.AuditLog{
		OccurredAt: time.Now(), ActorName: "林薇", Instance: "prod-1",
		Command: "select 1", Risk: "low", Result: "ok", ApprovalNo: "AP-1",
		Database: "shop", Operator: "linwei", Env: "prod", TierCode: "t1",
	}
	a.Hash = crypto.ChainHash("", auditPayload(a))
	if v := matchAuditRow("", a); v != 5 {
		t.Fatalf("matchAuditRow = %d, want 5", v)
	}
}

// sessionInTZ 在 db 那个 schema 上另开一个会话,并把它钉在一条连接上,好让
// SET TIME ZONE 对这个 handle 之后的每一次查询都算数(池里换一条连接,那条
// 连接上没设过时区)。
//
// 时区名用 POSIX 写法('+08' / 'GMT')而不是 'Asia/Shanghai' / 'UTC':本机这台
// Homebrew PostgreSQL 的 timezone 数据目录缺失,IANA 名字一律报
// invalid value for parameter "TimeZone"。偏移量是这条用例真正关心的东西。
func sessionInTZ(t *testing.T, db *gorm.DB, tz string) *gorm.DB {
	t.Helper()
	s := testsupport.NewSession(t, db)
	sqlDB, err := s.DB()
	if err != nil {
		t.Fatalf("取连接池: %v", err)
	}
	sqlDB.SetMaxOpenConns(1)
	sqlDB.SetMaxIdleConns(1)
	if err := s.Exec("SET TIME ZONE '" + tz + "'").Error; err != nil {
		t.Fatalf("SET TIME ZONE %s: %v", tz, err)
	}
	return s
}

// 真的写进 PostgreSQL、再真的读回来校验一遍 —— 写入与校验之间时区变了。
//
// 前两条用例钉的是 payload 函数本身;而这个 bug 的致命面在「写入与读回之间时区变了」,
// 只有过一遍数据库才压得到:appendAudit 用 time.Now()(进程本地时区)算哈希,
// VerifyAuditChain 用从库里读回来的 OccurredAt 重算。
//
// 两个变量各拨一次,因为现实里两个都会变:
//   - **会话时区**:写在 '+08' 的会话上,校验在 'GMT' 的会话上(pgx 读 TIMESTAMPTZ
//     时会话时区可能参与决定返回值挂的 Location);
//   - **进程时区**:time.Local 换成 UTC 再校验 —— 这就是"同一个网关换了台机器/
//     换了 TZ 环境变量重启,然后按下校验"。本机 pgx 恰好总把 TIMESTAMPTZ 解成
//     time.Local,所以只拨会话时区这一下打不中;进程时区这一拨是本机能复现那个
//     恒假警报的那一下。
func TestVerifyAuditChain_SurvivesTimezoneChangeBetweenWriteAndVerify(t *testing.T) {
	db := testsupport.NewDB(t)
	writer := sessionInTZ(t, db, "+08")
	verifier := sessionInTZ(t, db, "GMT")

	// 校验只对监督角色开放。角色行让库自己发 id(baseline 里是
	// GENERATED BY DEFAULT AS IDENTITY,显式插 id 不会推进序列)。
	role := &model.Role{Code: "audit", Name: "审计员", Layer: "platform"}
	if err := db.Create(role).Error; err != nil {
		t.Fatalf("建审计角色: %v", err)
	}
	actor := &model.User{ID: 1, Name: "林薇", RoleID: role.ID}

	// 走服务层写,不是直接 INSERT:哈希由 appendAudit 里那一处构造算出来。
	write := &Services{Repo: repository.New(writer)}
	for _, cmd := range []string{"SELECT 1", "UPDATE orders SET x = 1", "DELETE FROM orders"} {
		if a := write.appendAudit(actor, nil, cmd, "low", "executed", "", ""); a == nil || a.Hash == "" {
			t.Fatalf("审计行没写成:%q", cmd)
		}
	}

	// 进程时区换成 UTC —— 模拟换台机器(或换了 TZ 环境变量)重启后再按下校验。
	//
	// time.Local 是全局的,所以这一拨的前提是本包里没有 t.Parallel(今天一个也没有)。
	// 谁要给 internal/service 加并行,这条用例得先换一种拨法,否则它会去动别人的时间。
	utc, err := time.LoadLocation("UTC")
	if err != nil {
		t.Fatalf("load UTC: %v", err)
	}
	saved := time.Local
	time.Local = utc
	t.Cleanup(func() { time.Local = saved })

	rep, err := (&Services{Repo: repository.New(verifier)}).VerifyAuditChain(actor)
	if err != nil {
		t.Fatalf("VerifyAuditChain: %v", err)
	}
	if !rep.OK {
		t.Fatalf("链被报成断了,而它没断:brokenId=%d reason=%s", rep.BrokenID, rep.Reason)
	}
	if rep.Checked != 3 {
		t.Errorf("校验了 %d 行, want 3", rep.Checked)
	}
	if rep.ByVersion[currentAuditPayloadVersion] != 3 {
		t.Errorf("按 v%d 通过的行数 = %d, want 3(byVersion=%v)",
			currentAuditPayloadVersion, rep.ByVersion[currentAuditPayloadVersion], rep.ByVersion)
	}
}
